client/Windows/wf_cliprdr.c: handle malloc error
FreeRDP/FreeRDP pull request #10012
Opened 2024-03-22 19:26 UTC by chipitsine

## This is how are pull requests handled by FreeRDP
1. Every new pull request needs to build and pass the unit tests at https://ci.freerdp.com
1. At least 1 (better two) people need to review and test a pull request and agree to accept

## Preparations before creating a pull
* Rebase your branch to current master, no merges allowed!
* Try to clean up your commit history, group changes to commits
* Check your formatting! A _clang-format_ script can be found at ```.clang-format```
  * The cmake target ```clangformat``` reformats the whole codebase
* Optional (but higly recommended)
  * Run a clang scanbuild before and after your changes to avoid introducing new bugs
  * Run your compiler at pedantic level to check for new warnings

## To ease accepting your contribution
* Give the pull request a proper name so people looking at it have an basic idea what it is for
* Add at least a brief description what it does (or should do :) and what it's good for
* Give instructions on how to test your changes
* Ideally add unit tests if adding new features

## What you should be prepared for
* fix issues found during the review phase
* Joining our chat to talk to other developers or help them test your pull might accelerate acceptance
  * Matrix room : #FreeRDP:matrix.org (main)
  * XMPP channel: #FreeRDP#matrix.org@matrix.org (bridged)
  * IRC channel : #freerdp @ irc.oftc.net (bridged)
* Joining our mailing list <freerdp-devel@lists.sourceforge.net> may be helpful too.

## Please remove this text before submitting your pull!

2024-03-25 05:47 UTC, akallabeth requested changes
* missing error handling (e.g. `CloseClipboard` 
* `globlemem`  is also not checked for `NULL`
* I believe the root issue you wanted to fix is a `size == 0` case? that is also not handled properly

2024-03-25 05:47 UTC, akallabeth commented on client/Windows/wf_cliprdr.c
> +			if (buff == NULL)
missing error handling

2024-03-25 11:29 UTC, chipitsine commented
`I believe the root issue you wanted to fix is a size == 0 case? that is also not handled properly` - no, I caught that error from cppcheck. I'll have a look at suggestions as well

2024-04-03 07:16 UTC, akallabeth commented
@freerdp-bot test please

2024-04-03 07:16 UTC, akallabeth approved these changes

2024-04-03 08:45 UTC, merged