libfreerdp/crypto/certificate.c: handle malloc error
FreeRDP/FreeRDP pull request #10049
Opened 2024-04-05 08:44 UTC by chipitsine

2024-04-05 08:50 UTC, akallabeth requested changes
Please group your changes in one pull request if you have more of these small fixes in queue.

2024-04-05 08:50 UTC, akallabeth commented on libfreerdp/crypto/certificate.c
> +		EVP_PKEY_CTX_free(ctx);
use `goto out;` instead.

2024-04-05 09:31 UTC, chipitsine commented
> Please group your changes in one pull request if you have more of these small fixes in queue.

this was the last one

2024-04-05 09:31 UTC, chipitsine commented on libfreerdp/crypto/certificate.c
> +		EVP_PKEY_CTX_free(ctx);
makes sense. give me 5 min

2024-04-05 09:45 UTC, hardening commented
Looks ok for me but the history must be cleaned with just 1 commit with the 1 line change

2024-04-05 11:06 UTC, akallabeth commented
@freerdp-bot test

2024-04-05 21:10 UTC, hardening approved these changes

2024-04-06 05:11 UTC, akallabeth approved these changes

2024-04-06 05:11 UTC, merged