fix few resource leaks
FreeRDP/FreeRDP pull request #10056
Opened 2024-04-06 21:16 UTC by chipitsine

2024-04-06 22:12 UTC, hardening commented
@freerdp-bot can you test please ?

2024-04-07 07:03 UTC, akallabeth requested changes
LGTM, just one more free required

2024-04-07 07:03 UTC, akallabeth commented on libfreerdp/utils/http.c
> +			free(hostname);
same `free` missing in else branch

2024-04-07 08:43 UTC, chipitsine commented on libfreerdp/utils/http.c
> +			free(hostname);
thanks, added

2024-04-08 07:26 UTC, akallabeth approved these changes
LGTM, thank you!

2024-04-08 09:39 UTC, merged