[audin,winmm]Windows audio record support stereo
FreeRDP/FreeRDP pull request #10605
Opened 2024-09-14 08:28 UTC by cumt2010

/microphone:format:1, use `WAVE_FORMAT_PCM` format, 2 channels, it's almost all noise in Windows.
after comment this, it works very well, no noisy.

2024-09-14 09:14 UTC, akallabeth requested changes
this check was introduced exactly because of bugs with a lot of hardware (see comment)
so a little more explanation and your test cases are required to approve this.

2024-09-14 09:29 UTC, cumt2010 commented
> this check was introduced exactly because of bugs with a lot of hardware (see comment) so a little more explanation and your test cases are required to approve this.

OS: Windows 10 1703
Mic: Intel SST Audio Device (WDM)

by the way, i want use WAVE_FORMAT_OPUS format,  how to do?
1. What's the correct command line?
2. -DWITH_OPUS=ON

Thanks a lot.

2024-09-14 10:13 UTC, akallabeth commented
> by the way, i want use WAVE_FORMAT_OPUS format, how to do?

connect to `gnome-remote-desktop` ;)
check https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpeai/d04ffa42-5a0f-4f80-abb1-cc26f71c9452 for supported formats by windows servers. (basically boils down to some old compression formats, `PCM` and `AAC`)
 
>     1. What's the correct command line?
`/microphone` or `/sound`.
anything else is just for *specialized*  use cases, try to avoid parameters. (the server, aka remote end, does choose from what the client supports, so if you set something the server does not support and deactivate all other stuff you end up with a broken config)

2024-09-18 07:26 UTC, cumt2010 commented
> approve this.

Thanks very much, got it. 
Just use this parameter as bellow, record and playback works very well

Linux:
/microphone:sys:alsa,format:1
/sound:sys:alsa

Windows:
/microphone:format:1
/sound
add comment this, it works.

Now, A new issue for me:  the sound delay is getting worse. sometimes more than 30 secs.

2024-09-18 14:42 UTC, mfleisz commented
Just tested with wfreerdp using `/microphone /sound` and I was able to record/playback in the session without any glitches.
Closing as this doesn't fix anything generally broken.

2024-09-18 14:42 UTC, closed without merging