Fix HAVE_AF_VSOCK_H always being 0
FreeRDP/FreeRDP pull request #11016
Opened 2024-12-23 15:10 UTC by gpotter2

### Description

On current linux builds (at least I'm using 6.9.9) including `linux/vm_sockets.h` fails as so:
```
/usr/include/linux/vm_sockets.h:182:39: error: invalid application of ‘sizeof’ to incomplete type ‘struct sockaddr’
      182 |         unsigned char svm_zero[sizeof(struct sockaddr) -
          |                                       ^~~~~~
        /usr/include/linux/vm_sockets.h:183:39: error: ‘sa_family_t’ undeclared here (not in a function)
      183 |                                sizeof(sa_family_t) -
          |                                       ^~~~~~~~~~~
```

This means that currently, even if available, `HAVE_AF_VSOCK_H` is always false.

(You'd be right to point out that this should likely be fixed in `linux/vm_sockets.h` by adding an include to `sys/socket.h`... but I'm not familiar with Linux kernel development)

### Content of the PR

- add `sys/socket.h` in the check for it to pass when `linux/vm_sockets.h` is available.

2024-12-23 18:20 UTC, hardening approved these changes
Seems ok

2024-12-23 18:21 UTC, hardening commented
@freerdp-bot can you test please

2024-12-23 19:50 UTC, akallabeth requested changes
looks like the detection is not the only thing that requires adjustment for newer versions?

2024-12-23 20:04 UTC, gpotter2 commented
You seem to be right. I'll look into that to make sure it actually builds.

2024-12-23 21:12 UTC, gpotter2 commented
@freerdp-bot can you test please

2024-12-24 11:53 UTC, akallabeth commented
@freerdp-bot test

2024-12-24 12:06 UTC, akallabeth commented
@gpotter2 `debian32` runs on 6.8.8 and the fuzzers on `ubuntu-latest` github runners.
your advanced check is compiling though.

2024-12-24 12:23 UTC, gpotter2 commented
If I'm not mistaken ci-fuzzer runs a docker (https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-image/Dockerfile) which uses Ubuntu 20.04, which under Global Availability (GA) is stuck at 5.4 (https://ubuntu.com/security/livepatch/docs/livepatch/reference/kernels)

I don't really know for debian32, I didn't dig really deep.

Glad it builds ! On my machine it successfully sets the VSOCK to 1.

2024-12-24 13:16 UTC, merged