memory grows over time in wlfreerdp with /gfx:AVC444 fixed.
FreeRDP/FreeRDP pull request #6482
Opened 2020-09-18 12:40 UTC by xsumirx

- When running wlfreerdp with /gfx:AVC444 parameter. Resident size of the FreeRDP process gradually grows overtime and never shrinks even if the video paused or stoped.

- Sometimes wlfreerdp crashes when there are a lot of movement on the screen (like, dragging window fast in windows).

2020-09-19 06:47 UTC, akallabeth requested changes
Thank you for this pr,
But could you please remove the wlf_gfx.c implementation? It just duplicates the default fallback.
This is reserved for hardware accelerated backends (gl, vulkan, ximage)

2020-09-19 16:17 UTC, xsumirx commented
> Thank you for this pr,
> But could you please remove the wlf_gfx.c implementation? It just duplicates the default fallback.
> This is reserved for hardware accelerated backends (gl, vulkan, ximage)

Sure.

2020-09-20 20:35 UTC, hardening commented
Could you clean the log history so that we would have only 1 commit ?

2020-09-20 20:39 UTC, xsumirx commented
> Could you clean the log history so that we would have only 1 commit ?

Do you want me to squash both the commits into one commit ? Is that all ?

2020-09-20 21:06 UTC, hardening commented
> > Could you clean the log history so that we would have only 1 commit ?
> 
> Do you want me to squash both the commits into one commit ? Is that all ?

Yeah sure

2020-09-21 08:18 UTC, akallabeth commented
@freerdp-bot test

2020-09-21 08:19 UTC, akallabeth approved these changes
LGTM

2020-09-21 08:21 UTC, akallabeth commented
@xsumirx thank you for the pr. Just a question to understand: with this changes there is no more leak or it is just hidden?
I can not find a place where there are buffers handled differently here than before (just most of the events filtered)

2020-09-21 09:15 UTC, xsumirx commented
> @xsumirx thank you for the pr. Just a question to understand: with this changes there is no more leak or it is just hidden?
> I can not find a place where there are buffers handled differently here than before (just most of the events filtered)

@akallabeth From what I have observed after making those changes, that the resident size of the process doesn't rises beyond a certain memory size (105MB in my case), but earlier before these changes,  a very long test of about 9-10 hours of continues video play can result the resident size of above 800MB in ram, which was not normal.

As far as my narrow understanding about the internals of FreeRDP goes, It seems that, marking invalid flag of primary gdi in begin_paint function even before actually rendering the frame, somehow leads FreeRDP to allocate more memory for frames overtimes.

The other change in uwac-window.c is a very crucial check, I have encountered that in many instances, I got negative numbers for either width or heigh. which lead to whole process crash.

2020-09-21 09:22 UTC, akallabeth commented
@xsumirx that sounds strange. many of our clients use the same pattern with `begin` and `end_paint`, so I doubt that has something to do with your ram usage.
the second fix with the `width>0` check on the other hand seems legit.

2020-09-21 09:30 UTC, xsumirx commented
If you can run some test with above command, and watch over res size in ps command. I sure will see the difference. You have to run the test for minimum of 2 hours.

2020-09-21 10:35 UTC, akallabeth commented
@xsumirx ok, please run that. I´ve run a test last month with a custom client that utilizes the same logic, test ran for a week with automated tests and the memory usage did not increase.
So, maybe we have some other issue with the wayland client hidden.

2020-09-21 10:59 UTC, xsumirx commented
> @xsumirx ok, please run that. I´ve run a test last month with a custom client that utilizes the same logic, test ran for a week with automated tests and the memory usage did not increase.
> So, maybe we have some other issue with the wayland client hidden.

Ok. I don't think, I am gonna run anymore test now. Because I already did so very rigorously. I am not sure why you haven't got this issue with Wayland considering that you had run the test with the same parameter as I had mentioned above and played fullscreen video consistently for whole test time.

Let me know, If this pr not relevant from your understanding and not suitable to be proceeded further. I will close it.

2020-09-21 11:07 UTC, akallabeth commented
@xsumirx no, your pr is relevant ;)
What I did was not a test with the wayland client, but a custom one.
FreeRDP uses the same core routines to do most of the stuff and only what you do in the functions for the client differs, so if you have a memory leak with the `begin_paint` and `end_paint` cycle, it must be in all clients or there is something else wrong with the client.
That is why I´m curious. Being content with hiding bugs never is a good strategy in the long run. (that is the reason for the inquiry)

2020-09-21 15:25 UTC, xsumirx commented
> @xsumirx no, your pr is relevant ;)
> 
> What I did was not a test with the wayland client, but a custom one.
> 
> FreeRDP uses the same core routines to do most of the stuff and only what you do in the functions for the client differs, so if you have a memory leak with the `begin_paint` and `end_paint` cycle, it must be in all clients or there is something else wrong with the client.
> 
> That is why I´m curious. Being content with hiding bugs never is a good strategy in the long run. (that is the reason for the inquiry)

That sounds good.

So, Can you guide me how can i identify the exact cause of the issue. 

Any, strategy that i need to follow ?

2020-09-22 08:00 UTC, akallabeth commented
@xsumirx No easy strategy I can think of now. I´ll check the wayland client as soon as I have time for some tests. Sorry to keep you waiting :/

2022-02-14 14:06 UTC, akallabeth commented
@freerdp-bot test

2022-02-15 08:52 UTC, akallabeth commented
@freerdp-bot test

2022-02-15 09:47 UTC, akallabeth commented
@freerdp-bot test

2022-02-15 10:58 UTC, merged