Fixed missing check for fastpath input messages
FreeRDP/FreeRDP pull request #6742
Opened 2021-01-22 07:25 UTC by akallabeth

Input events are only allowed after a connection was established
(connection state is active)
This check aborts input sending when done before that.

2021-01-22 11:54 UTC, mfleisz requested changes

2021-01-22 11:54 UTC, mfleisz commented on libfreerdp/core/fastpath.c
> +	state = rdp_client_get_state(rdp);
`rdp` seems to be uninitialized here

2021-01-25 08:24 UTC, mfleisz approved these changes
LGTM

2021-01-25 08:24 UTC, merged

2021-02-01 09:27 UTC, krajorama commented
Tested OK with Guacamole 1.3.0 + FreeRDP 2.2.0 + this fix backported.

2021-02-04 07:55 UTC, akallabeth commented
@krajorama good to know. but be aware, this is just fixing (or hiding) bad application behavior, guacamole needs to fix this properly, as there are other messages as well that are not allowed before a connection is properly established.

2021-02-08 07:42 UTC, krajorama commented
@akallabeth Sounds reasonable, but how would Guacamole know when a redirect starts and it needs to stop sending messages? I was trying to find a solution, but all I could find was that I can subscribe to the end of the redirect: PubSub_SubscribeActivated(context->pubSub, my_callback);

Thanks in advance, krajo

2021-02-08 08:16 UTC, akallabeth commented
@krajorama that is a reasonable approach. The session state is `ready for use` when that happened (it is basically the same check we do with this patch)

2021-02-08 08:39 UTC, krajorama commented
@akallabeth , right I've tested it, but it is NOT the full solution, since I don't know when to stop sending the messages. The scenario is this: I connect to the server, it shows me a welcome screen, I interact with it - so I have to send keyboard/mouse events. Then there is a redirect. The problem before your patch was that if I move my mouse during the redirect, the connection is failed by the server because of protocol violation.

So the question is : how do I know in Guac that I should stop sending messages?

2021-02-08 09:35 UTC, akallabeth commented
@krajorama Indeed, there seems to be a missing event that propagates the current connection state. I´ll create a patch for that.