Add support for OpenBSD sndio audio subsystem
FreeRDP/FreeRDP pull request #6857
Opened 2021-03-03 19:14 UTC by ledeuns

This PR adds support for OpenBSD sndio audio subsystem.

> $ xfreerdp /v:rdp-server /u:user /sound:sys:sndio

will enable sound on the remote machine.

2021-03-03 20:39 UTC, akallabeth commented
@freerdp-bot test

2021-03-03 20:47 UTC, akallabeth requested changes
Thank you, a really nice addition!
Please check the comments, when resolved this can be merged.

Please also run `clang-format` on the changes, the pull request tester checks the formatting style for new contributions.

2021-03-03 20:47 UTC, akallabeth commented on winpr/libwinpr/CMakeLists.txt
> +if (!OpenBSD)
is this syntax supported by `CMake` ? I think this should be `if (NOT OpenBSD)`

2021-03-03 20:47 UTC, akallabeth commented on CMakeLists.txt
> +if(EPOLLSHIM)
Where is ` EPOLLSHIM` defined? I can only find a `Find` module when searching for this, but not default in ` CMake`

2021-03-07 10:40 UTC, ledeuns commented
Th PR is mixed with another diff. Closing and will reopen with only changes needed for sndio

2021-03-07 10:40 UTC, closed without merging