Improvement: Add a way to get timezone from environment.
FreeRDP/FreeRDP pull request #7175
Opened 2021-07-16 08:01 UTC by dev-ddoe

Firstly get timezone from environment. If not present, use file method

2021-07-19 08:01 UTC, akallabeth requested changes

2021-07-19 08:13 UTC, dev-ddoe commented on winpr/libwinpr/timezone/timezone.c
> +	if (tzenv) {
good point. I will fix that.

2021-07-19 08:13 UTC, dev-ddoe commented on winpr/libwinpr/timezone/timezone.c
> +	char* tzenv = getenv("TZ");
good point. I will fix that.

2021-07-19 08:54 UTC, akallabeth commented
@freerdp-bot test

2021-07-19 08:55 UTC, akallabeth commented on winpr/libwinpr/timezone/timezone.c
> +	if (nSize) {
style wrong, run `clang-format` on your changes.

2021-07-19 09:02 UTC, dev-ddoe commented on winpr/libwinpr/timezone/timezone.c
> +	if (nSize) {
Updated

2021-07-20 13:19 UTC, akallabeth commented
@freerdp-bot test

2021-07-20 13:20 UTC, akallabeth approved these changes

2021-07-20 13:31 UTC, merged