WinPR::Clipboard: Refactor synthetic file
FreeRDP/FreeRDP pull request #8246
Opened 2022-09-26 08:21 UTC by KangLin

2022-09-26 08:46 UTC, akallabeth requested changes
Mostly LGTM, except:

* The `WCHAR` print and comparison must make sure to work with `WCHAR` and not `wchar_t` (the latter is system dependent and might be different from `UCS2/UTF16`)
* Remove the `TestUri` parts, already done that in #8232

2022-09-26 08:46 UTC, akallabeth commented on winpr/libwinpr/clipboard/synthetic_file.c
> +typedef SSIZE_T ssize_t;
this is wrong, newer windows versions define this type

2022-09-26 08:46 UTC, akallabeth commented on winpr/libwinpr/clipboard/synthetic_file.c
> +		if (*c == L'/')
`Be careful with `L'somestring'`, windows understands `UCS-2/UTF16` most other systems `UCS4/UTF32`

2022-09-26 08:46 UTC, akallabeth commented on winpr/libwinpr/clipboard/synthetic_file.c
> +	swprintf(namebuf, L"%s/*.*", local_name);
`Be careful with `L'somestring'`, windows understands `UCS-2/UTF16` most other systems `UCS4/UTF32` so the resulting string will be broken on many systems

2022-09-26 08:46 UTC, akallabeth commented on winpr/libwinpr/clipboard/synthetic_file.c
> +	if ((_wcscmp(pFileData->cFileName, L".") == 0) || (_wcscmp(pFileData->cFileName, L"..") == 0))
`Be careful with `L'somestring'`, windows understands `UCS-2/UTF16` most other systems `UCS4/UTF32`

2022-09-26 08:46 UTC, akallabeth commented on winpr/libwinpr/clipboard/synthetic_file.c
> +	buffer[len_dir] = L'/';
`Be careful with `L'somestring'`, windows understands `UCS-2/UTF16` most other systems `UCS4/UTF32`

2022-09-26 11:32 UTC, akallabeth commented
@freerdp-bot test

2022-09-26 11:39 UTC, akallabeth commented
@freerdp-bot test

2022-09-26 11:39 UTC, akallabeth approved these changes
LGTM

2022-09-26 11:40 UTC, akallabeth commented
@KangLin I´ve fixed the remaining issues with this pr, thank you for the nice addition!

2022-09-26 11:47 UTC, akallabeth commented
@freerdp-bot test

2022-09-26 11:51 UTC, akallabeth commented
@freerdp-bot test

2022-09-26 12:01 UTC, merged

2022-09-26 13:33 UTC, KangLin commented
@akallabeth Why is the WCHAR definition typedef __uint16 WCHAR, not typedef wchar_t WCHAR？

2022-09-27 05:21 UTC, akallabeth commented
@KangLin because it is the windows `WCHAR` type, which is always `16bit` whereas `wchar_t` is system dependent (most linux systems use `32bit` unicode)

2022-09-27 06:52 UTC, KangLin commented
@akallabeth I saw the instructions in the unicode.c file.
But in general (string functions), WCHAR is defined as wchar_t. Only in FILEDESCRIPTORW need to convert to int16.
Is it too expensive to do this?
Also, if you print WCHAR?

2022-09-27 06:55 UTC, akallabeth commented
@KangLin no, the type is used all over the place, it is core part of many protocol messages. (as `uint16`)