Add support to send a ServerRedirection PDU
FreeRDP/FreeRDP pull request #8252
Opened 2022-09-27 15:33 UTC by jotolo2

This PR should add the functionality of sending a Server Redirection PDU to a connected RDP client.

It has been implemented following the style of `core.redirection`.

I have tested with an xfreerdp client and recognises all fields properly. The client reconnects as expected.

I'm not sure if this method should be located in another place. It would be helpful if someone who knows more about this could point where it would make more sense to be located.

I assume this should be on the `stable-2.0` branch too.

Thank you.

2022-09-27 16:43 UTC, hardening commented on libfreerdp/core/peer.c
> +	Stream_Write_UINT16(s, length);
We shall have a `if (!Stream_EnsureRemainingCapacity(s, length)) ...` here to ensure that the stream has enough room for what we want to write in it

2022-09-27 16:44 UTC, hardening approved these changes
Except my remark, LGTM

2022-09-27 16:45 UTC, hardening commented
@freerdp-bot test that please

2022-09-27 19:45 UTC, hardening commented
@freerdp-bot can you re test that ?

2022-09-28 05:26 UTC, akallabeth commented on libfreerdp/core/peer.c
> +		int i;
`i` should match type with `targetNetAddressesCount`

2022-09-28 05:26 UTC, akallabeth commented on libfreerdp/core/peer.c
> +		int i;
`i` should match type with `targetNetAddressesCount`

2022-09-28 05:27 UTC, akallabeth commented on libfreerdp/core/peer.c
> +		int i;
`i` should match type with `targetNetAddressesCount`

2022-09-28 05:29 UTC, akallabeth requested changes
Please address the (minor) remarks and run `git clang-format` on the source to enforce coding guidelines.
Other than that LGTM, nice work!

2022-09-28 09:22 UTC, akallabeth approved these changes
LGTM

2022-09-28 09:22 UTC, akallabeth commented
@freerdp-bot test

2022-09-28 11:54 UTC, merged