Autodetect refactor module
FreeRDP/FreeRDP pull request #8272
Opened 2022-10-04 14:02 UTC by akallabeth

* First in a series of refactoring pull requests trying to improve client and server state machine granularity.

2022-10-04 14:15 UTC, akallabeth commented
@freerdp-bot please test this!

2022-11-03 09:07 UTC, MartinHaimberger requested changes

2022-11-03 09:50 UTC, akallabeth commented on libfreerdp/core/activation.c
> -	WINPR_ASSERT(s);
Done in `rdp_finalize_set_flag`

2022-11-03 09:51 UTC, akallabeth commented on libfreerdp/core/autodetect.c
>  	rdpAutoDetect* autoDetect = (rdpAutoDetect*)calloc(1, sizeof(rdpAutoDetect));
fixed

2022-11-03 10:24 UTC, MartinHaimberger approved these changes

2022-11-03 10:56 UTC, merged