core: Add possibility to distinguish between auth cancelled and no creds
FreeRDP/FreeRDP pull request #8687
Opened 2023-02-13 11:41 UTC by mfleisz

Currently if the authentication callback returns `FALSE` the utils function handle this as scenario as no credentials provided (returns `AUTH_NO_CREDENTIALS)`.

This PR introduces a new `auth_status` called `AUTH_CANCELLED` that is returned if the authentication callback returns `FALSE`. If the callback returns `TRUE` and username or password are empty the util function will continue to return `AUTH_NO_CREDENTIALS`.

The PR also fixes some incorrect returns in RPC over HTTP gateway code.

2023-02-13 12:35 UTC, mfleisz commented
@freerdp-bot test

2023-02-14 06:57 UTC, akallabeth requested changes
Overall LGTM except the wrong return value

2023-02-14 06:57 UTC, akallabeth commented on libfreerdp/core/gateway/rpc_bind.c
> +			return FALSE;
wrong return type, function returns `int`

2023-02-14 06:57 UTC, akallabeth commented on libfreerdp/core/gateway/ncacn_http.c
>  	credssp_auth_setup_client(auth, "HTTP", settings->GatewayHostname, &identity, NULL);
not your code, but missing return check

2023-02-14 07:10 UTC, akallabeth approved these changes

2023-02-14 07:21 UTC, mfleisz commented on libfreerdp/core/gateway/ncacn_http.c
>  	credssp_auth_setup_client(auth, "HTTP", settings->GatewayHostname, &identity, NULL);
@akallabeth thx for fixing 👍

2023-02-14 07:43 UTC, merged