fix and improve cJSON detection
FreeRDP/FreeRDP pull request #8781
Opened 2023-03-10 19:59 UTC by awakecoding

With the latest commit, CMake generation fails if cJSON is missing (it uses get_filename_component on empty variables). I refactored the detection code to be more robust and less verbose as it tries to detect cJSON using both CMake export scripts and manual detection that does not rely on CMake export scripts or pkg-config (that's actually what I'm using myself in my conan builds)

2023-03-10 19:59 UTC, awakecoding commented
@fifthdegree FYI

2023-03-10 21:35 UTC, akallabeth requested changes
nice one, except the little typo

2023-03-10 21:35 UTC, akallabeth commented on libfreerdp/CMakeLists.txt
> +        NAMES csjon/cJSON.h
this path might not be detected :)

2023-03-10 22:14 UTC, awakecoding commented
@akallabeth good catch - I ended up rewriting it to make it a recommended feature that gets turned on automatically if detected, and I used WITH_CJSON in the code rather than CJSON_FOUND (allows building without it even if it's detected)

2023-03-11 07:19 UTC, akallabeth approved these changes
LGTM

2023-03-11 07:20 UTC, merged