mcs: drop a server-side warning on FreeRDP_ChannelDefArray::len
FreeRDP/FreeRDP pull request #8929
Opened 2023-04-26 10:09 UTC by hardening

Server side we often see "FreeRDP_ChannelDefArray::len expected to be >= 31, but have XXX", where XXX is lower than 31.

This patche fixes that, the old code was setting the size of ChannelDefArray to the number of ChannelCount, which is usually not what we want. We want to keep it to 31 and have ChannelCount indicate how many of these channels are used.

2023-04-26 11:12 UTC, akallabeth requested changes
Looks buggy, what if `FreeRDP_ChannelCount` is larger than `FreeRDP_ChannelDefArraySize`?

2023-04-26 11:32 UTC, hardening commented
> Looks buggy, what if `FreeRDP_ChannelCount` is larger than `FreeRDP_ChannelDefArraySize`?

This cannot happen, as the treatment in mcs is limited to what is possible in the packet: 31 channels.
Just to clarify, `FreeRDP_ChannelDefArraySize` is the capacity of `FreeRDP_ChannelDefArray`, while `FreeRDP_ChannelCount` is the number used items. So there's no real real reason to change the capacity of `FreeRDP_ChannelDefArray`.

2023-04-26 11:53 UTC, akallabeth commented
@hardening so, `freerdp_settings_clone`  et al work correctly in that case? I think I remember some issues during copy operations, so maybe have a look there too

2023-04-27 06:31 UTC, akallabeth approved these changes
LGTM

2023-04-27 06:37 UTC, merged