Improve Azure AD communication
FreeRDP/FreeRDP pull request #9127
Opened 2023-07-02 16:21 UTC by fifthdegree

2023-07-03 07:22 UTC, akallabeth reviewed
* I´ve been working on getting webview to support more backends aside from `Qt` with https://github.com/FreeRDP/FreeRDP/pull/9073 (not quite finished yet for platforms other than linux)
* introducing the `curl` dependency might better be optional (the suggestion I made in matrix was to replace the whole http parser in freerdp, not just here ;))

2023-07-03 07:22 UTC, akallabeth commented on CMakeLists.txt
> +	find_feature(CJSON REQUIRED ${CJSON_FEATURE_PURPOSE} ${CJSON_FEATURE_DESCRIPTION})
better switch to [find_package](https://cmake.org/cmake/help/latest/command/find_package.html)

2023-07-03 07:22 UTC, akallabeth commented on CMakeLists.txt
> +	find_feature(Curl REQUIRED ${CURL_FEATURE_PURPOSE} ${CURL_FEATURE_DESCRIPTION})
better switch to [find_package](https://cmake.org/cmake/help/latest/command/find_package.html)

2023-07-03 07:22 UTC, akallabeth commented on client/SDL/sdl_webview.cpp
> +std::string sdl_webview_get_auth_code(QString url)
shouldn´ t this function be `static`?

2023-07-03 07:55 UTC, hardening commented
>     * introducing the `curl` dependency might better be optional (the suggestion I made in matrix was to replace the whole http parser in freerdp, not just here ;))

I guess that `libcurl` is able to handle the specific things of rdg protocol (like the almost never ending request) when not using the "easy" interface.
I'm seeing that libcurl-ws could also do websocket for us...

2023-07-03 08:22 UTC, akarl10 commented
> > ```
> > * introducing the `curl` dependency might better be optional (the suggestion I made in matrix was to replace the whole http parser in freerdp, not just here ;))
> > ```
> 
> I guess that `libcurl` is able to handle the specific things of rdg protocol (like the almost never ending request) when not using the "easy" interface. I'm seeing that libcurl-ws could also do websocket for us...

we would first make sure one thing:
How a underlying socket can be forced for a specific request.
This will be needed for Negotiate/NTLM authentication since this type of requests are not (like everthing else in HTTP) stateless. libcurl would support NTLM and Negotiate, but I think FreeRDP's impementation is better suited and I think we don't want different behaviour in this case.

Also for example RDG_OUT_DATA first needs to get a 200 OK with a empty body on the underlying connection before the actual RDG_OUT_DATA is sent on the same connection (except a 101 is returned, then a websocket connection is used -> this is opportunistic, don't know if that is easy to do in libcurl-ws)

2023-07-03 09:26 UTC, akallabeth commented
@hardening @akarl10 that sounds like we should split this pr.
* the changes regarding `libcurl` might be ok or not, but it looks like there needs to be some agreement on that first
* the callbacks look good (although it could be argued to refactor the initial AAD callback so it can handle both types)

2023-07-03 09:48 UTC, akarl10 commented
@akallabeth just to make that clear: I'm not against libcurl in the gateway case, I just wanted to say that it might be harder then we expect in that case. For the cases where we can use the "easy" api, like token fetching and the arm/connections/ endpoint libcurl for sure is the better option.

The idea @fifthdegree had that if you use AAD you need cJSON and libcurl is not that bad I think (that is porting aad.c and probably arm.c to libcurl).

The second step then might really be porting other things in gateway/ to libcurl, and when all is ported remove http.c/h, and websocket.c/h

one thing that we might not forget: /tls:seclevel:0 might be required for gateway server < 2012, so we probably need to set such a option also for libcurl

2023-07-03 09:59 UTC, akallabeth commented
@akarl10 I got that, but it might take some time to implement. adding `libcurl` in between (while still using the custom `http` and `websockets` parsing) might not be the best approach.
so, I´m just suggesting that we postpone this until we have resolved the questions surrounding `libcurl` before adding it as a dependency.
(side note, `seclecel` related stuff is mostly `ssl` related, but you might be right that `curl` also tries to do stuff there.

2023-07-03 13:00 UTC, hardening commented
We might find equivalent for SecLevel in libcurl

2023-07-03 14:14 UTC, fifthdegree commented
I initially intended to change the gateway over to libcurl too, but haven't found the time for that yet. We will need to provide a callback function to openssl for certificate verification and to compute SecBindings. The curl docs label their websocket api as experimental; I'm not sure if that means the api might still change

2023-07-03 17:02 UTC, akarl10 commented
just a quick note on libcurl ws support: I think ubuntu (maybe debian too) have not enabled that in the delivered libcurl. Sure, we might compile against a non system libcurl, but I think this would complicate things considerably

2023-07-19 13:21 UTC, akallabeth commented
@fifthdegree where are we at for this pr?

2023-07-19 15:33 UTC, akallabeth commented
@fifthdegree hmm, we are thinking about releasing a 3.0-beta and it might be a nice thing to have in there and introduce the `curl` rewrite later on?

2023-07-19 17:42 UTC, fifthdegree commented
OK, took out the curl stuff and added a very simple function under utils for doing standard http requests. Then we can just use curl there for all standard requests.

2023-07-20 05:55 UTC, akallabeth requested changes
nicely done.
A few small remarks still, but overall LGTM

2023-07-20 05:55 UTC, akallabeth commented on client/SDL/sdl_webview.hpp
> +	BOOL sdl_webview_get_avd_access_token(freerdp* instance, char** token);
Maybe a good idea to unify these.
something like `GetAccessToken(freerdp* instance, int tokenType, char** token, ...);` might do the trick.

2023-07-20 05:55 UTC, akallabeth commented on libfreerdp/utils/http.c
> +	if (!url || strlen(url) < 8 || strncmp(url, "https://", 8) != 0 ||
might use `strnlen(url, 8)` here as we are not interested in full length.

2023-07-20 05:55 UTC, akallabeth commented on libfreerdp/utils/http.c
> +	hostname = calloc(1, path - (url + 8) + 1);
`strdup(path)`?

2023-07-20 05:55 UTC, akallabeth commented on libfreerdp/utils/http.c
> +		*response = calloc(1, *response_length + 1);
might move the allocation after checking validity of length

2023-07-20 05:56 UTC, akallabeth commented
@freerdp-bot test please

2023-07-20 06:32 UTC, akallabeth commented
@fifthdegree will fix these issues myself, so don´t bother ;)

2023-07-20 06:44 UTC, akallabeth commented
@freerdp-bot test please

2023-07-20 06:54 UTC, akallabeth commented
@freerdp-bot test please

2023-07-20 07:05 UTC, akallabeth commented
@freerdp-bot test again please

2023-07-20 07:12 UTC, akallabeth commented
@freerdp-bot test please

2023-07-20 07:24 UTC, akallabeth commented
@freerdp-bot test again please

2023-07-20 07:24 UTC, akallabeth approved these changes
LGTM

2023-07-20 07:27 UTC, akallabeth commented
@freerdp-bot and again you test please

2023-07-20 08:21 UTC, akallabeth commented
@freerdp-bot test again please

2023-07-20 08:45 UTC, akallabeth commented
@freerdp-bot test again please

2023-07-20 09:16 UTC, akallabeth commented
@freerdp-bot test please

2023-07-20 09:52 UTC, akallabeth commented
@freerdp-bot test please

2023-07-20 10:14 UTC, akallabeth commented
@freerdp-bot test

2023-07-20 11:45 UTC, akallabeth commented
@freerdp-bot test again please

2023-07-20 12:20 UTC, merged