Do not fail on certificates without subject
FreeRDP/FreeRDP pull request #9276
Opened 2023-08-08 15:34 UTC by ggirol-rc

It is possible to implement an rdp client that accepts certificates by fingerprint by using VerifyCertificateEx. In case the server uses a certificate without subject (which, apparently, is not mandated by X509) freerdp_certificate_data_load_cache fails and the certificate is refused even before calling VerifyCertificateEx. This commit changes freerdp_certificate_data_load_cache to consider that missing subject is the same as an empty string.

Also downgrade the log message complaining about missing subject and issuer to a warning.

To generate a certificate without these fields, you can run:
```
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/"
```

2023-08-09 09:01 UTC, hardening approved these changes
Seems ok for me

2023-08-09 10:32 UTC, hardening commented
@freerdp-bot can you test please ?

2023-08-16 08:20 UTC, hardening commented
@ggirol-rc please rebase that PR so that the CI is happy

2023-08-16 08:33 UTC, ggirol-rc commented
done

2023-08-16 13:23 UTC, hardening commented
@freerdp-bot can you test that correctly now please ?

2023-08-21 09:57 UTC, akallabeth commented
@ggirol-rc you are correct that is not mandated by `X509` but could you please provide some case this makes any sense?

the implementation in `RDP` do require some fields that are not mandated by `X509` and I consider the subject one of these (as it is more or less the only human readable identifier for a server, just like a website certificate without the URL does not make much sense)

2023-08-21 09:58 UTC, akallabeth requested changes
need an argument to convince me this is actually a good idea.

2023-08-21 11:46 UTC, hardening commented
I'm also hitting the case with a server that exposes a certificate with no subject, and I did no fancy configuration with it...

2023-08-21 11:48 UTC, hardening commented
The fix is either you have empty issuer/subject (this PR) or you have certs callback robust to NULL issuer / subject.

2023-08-21 13:52 UTC, akallabeth commented on libfreerdp/crypto/certificate_data.c
> +		data->cached_issuer = calloc(1, 1);
just remove the check, `NULL` should stay `NULL`

2023-08-21 13:52 UTC, akallabeth commented on libfreerdp/crypto/certificate_data.c
> +		data->cached_subject = calloc(1, 1);
just remove the check, `NULL` should stay `NULL`

2023-08-21 14:03 UTC, akallabeth approved these changes

2023-08-21 14:03 UTC, merged