optimize idwt extrapolate decoder with neon
FreeRDP/FreeRDP pull request #9290
Opened 2023-08-15 10:04 UTC by nero-ruijie

2023-08-15 13:32 UTC, hardening commented
@freerdp-bot can you give a test please ?

2023-08-16 08:20 UTC, mfleisz commented
@nero-ruijie there are some formatting issues with your PR - please run clang-format on the changed files

2023-08-16 08:28 UTC, nero-ruijie commented
> @nero-ruijie there are some formatting issues with your PR - please run clang-format on the changed files

i've tried clang-format which resulted in original codes also been impacted.
So, just format the additional code or commit the entire updates?

2023-08-16 13:21 UTC, hardening commented
> > @nero-ruijie there are some formatting issues with your PR - please run clang-format on the changed files
> 
> i've tried clang-format which resulted in original codes also been impacted. So, just format the additional code or commit the entire updates?

Only the files you've changed.

2023-08-17 02:20 UTC, nero-ruijie commented
> > > @nero-ruijie there are some formatting issues with your PR - please run clang-format on the changed files
> > 
> > 
> > i've tried clang-format which resulted in original codes also been impacted. So, just format the additional code or commit the entire updates?
> 
> Only the files you've changed.

done

2023-08-17 07:40 UTC, nero-ruijie commented
> @nero-ruijie please pack your changes in 1 commit (no "format code" commit)

done

2023-08-18 09:36 UTC, hardening commented
@freerdp-bot can you test please ?

2023-08-21 08:33 UTC, akallabeth requested changes

2023-08-21 08:33 UTC, akallabeth commented on libfreerdp/codec/progressive.c
> +	if (!progressive->rfx_context->dwt_2d_extrapolate_decode)
wrong place, move to where `dwt_2d_decode` is initialized to default (e.g. `rfx_context_new_ex`)

2023-08-21 08:33 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +static __inline void __attribute__((__gnu_inline__, __always_inline__, __artificial__))
we have the `INLINE` macro for this in `FreeRDP`

2023-08-21 08:33 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +rfx_idwt_extrapolate_horiz_neon(const INT16* pLowBand, size_t nLowStep, const INT16* pHighBand,
you might want to experiment with the `restrict` keyword for optimization here

2023-08-21 08:33 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +rfx_idwt_extrapolate_vert_neon(const INT16* pLowBand, size_t nLowStep, const INT16* pHighBand,
you might want to check the `restrict` keyword for arguments here

2023-08-21 08:33 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +rfx_dwt_2d_decode_extrapolate_block_neon(INT16* buffer, INT16* temp, size_t level)
use macro `INLINE`

2023-08-21 08:33 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +{
`WINPR_ASSERT` arguments to better detect `API` misuse

2023-08-21 08:34 UTC, akallabeth commented
@nero-ruijie thank you for this contribution. I just did a small review (did not do thorough tests) and the changes look like a nice addition, but a few things need adjustment first.

2023-08-22 03:03 UTC, nero-ruijie commented
@freerdp-bot test

2023-08-22 03:16 UTC, nero-ruijie commented
> @nero-ruijie thank you for this contribution. I just did a small review (did not do thorough tests) and the changes look like a nice addition, but a few things need adjustment first.
@akallabeth I have updated the code as you commented. Pls check again.

2023-08-22 05:51 UTC, akallabeth requested changes
some more in depth review.

code looks good (except some assertions missing and loop variable type mismatches).
will check functionality later when I have time, raspberry is slow on compile :)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/progressive.c
> +	progressive_rfx_dwt_2d_decode_block(&buffer[3807], temp, 3);
`WINPR_ASSERT` arguments before dereference

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/progressive.c
> +		progressive->rfx_context->dwt_2d_extrapolate_decode(buffer, temp);
`WINPR_ASSERT` function pointer

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +static INLINE void __attribute__((__gnu_inline__, __always_inline__, __artificial__))
remove `__attribute__`, we try not to assume any compiler (well, not 100% possible but this is already inline, so the keywords are mostly for debugging, right?)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +rfx_idwt_extrapolate_horiz_neon(const INT16* restrict pLowBand, size_t nLowStep,
`WINPR_ASSERT` function arguments (pointers)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +static INLINE void __attribute__((__gnu_inline__, __always_inline__, __artificial__))
remove the `__attribute__`

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +rfx_idwt_extrapolate_vert_neon(const INT16* restrict pLowBand, size_t nLowStep,
`WINPR_ASSERT` arguments

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +static INLINE void __attribute__((__gnu_inline__, __always_inline__, __artificial__))
remove `__attribute__`

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +	for (y = 0; y < nDstCount; y++)
we´re using modern `C` now, you can declare the variable in the loop like `for (size_t y=0; y<nDstCount; y++)`
also ensure the type matches (you have `int y` and `size_t nDstCount` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +		for (n = 0; n < batchSize; n += 8)
we´re using modern `C` now, you can declare the variable in the loop like `for (size n = 0; n < batchSize; n += 8)`
also ensure the type matches (you have `int y` and `size_t batchSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +		for (n = 0; n < batchSize; n += 8)
we´re using modern `C` now, you can declare the variable in the loop like `for (size n = 0; n < batchSize; n += 8)`
also ensure the type matches (you have `int y` and `size_t batchSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +	for (n = 0; n < forceBandSize; n++)
we´re using modern `C` now, you can declare the variable in the loop like `for (size n = 0; n < forceBandSize; n ++)`
also ensure the type matches (you have `int y` and `size_t forceBandSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +	for (n = 0; n < forceBandSize; n++)
we´re using modern `C` now, you can declare the variable in the loop like `for (size n = 0; n < forceBandSize; n ++)`
also ensure the type matches (you have `int y` and `size_t forceBandSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +	int batchSize = (nDstCount >> 3) << 3;
1. wrong data type, truncation from `size_t` to `int`
2. can also be written `const size_t batchSize = nDstCount & ~0x07` or `const size_t batchSizxe = nDstCount & FFFFFFFFFFFFFFF8`

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +		for (x = 0; x < batchSize; x += 8)
we´re using modern C now, you can declare the variable in the loop like `for (size x = 0; x < batchSize; x++)`
also ensure the type matches (you have `int x` and `size_t` for `batchSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +		for (x = 0; x < batchSize; x += 8)
we´re using modern C now, you can declare the variable in the loop like `for (size x = 0; x < batchSize; x++)`
also ensure the type matches (you have `int x` and `size_t` for `batchSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +		for (x = 0; x < batchSize; x += 8)
we´re using modern C now, you can declare the variable in the loop like `for (size x = 0; x < batchSize; x++)`
also ensure the type matches (you have `int x` and `size_t` for `batchSize` here)

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +rfx_dwt_2d_decode_extrapolate_block_neon(INT16* buffer, INT16* temp, size_t level)
`WINPR_ASSERT` pointer arguments

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +	HL = &buffer[offset];
you can declare the variables mid code now (`C99`) and better make them `const` if you do not intend to modify them

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +		{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:51 UTC, akallabeth commented on libfreerdp/codec/rfx_neon.c
> +			{
no braces required for one liners

2023-08-22 05:52 UTC, akallabeth commented
@freerdp-bot test

2023-08-22 07:44 UTC, nero-ruijie commented
> some more in depth review.
> 
> code looks good (except some assertions missing and loop variable type mismatches). will check functionality later when I have time, raspberry is slow on compile :)

Code updated again as you commented with one exception:
H/L/HL/... band buffer ptr is keept as non-const due to both buffer(idwt data src and result buffer) and temp (buffer) will be updated in the final, especially in rfx_idwt_extrapolate_horiz_neon, medial data is stored in pLowBand for performance reason(also refer to rfx_dwt_2d_decode_block_horiz_NEON) where pLowBand is the input data buffer and is marked "const" in progressive_rfx_idwt_x.

2023-08-22 08:24 UTC, akallabeth approved these changes
LGTM

2023-08-22 08:25 UTC, akallabeth commented
@freerdp-bot test

2023-08-22 08:54 UTC, merged