Fixes clang error
FreeRDP/FreeRDP pull request #9373
Opened 2023-09-11 00:37 UTC by wangmingyu84

error: incompatible function pointer types assigning to 'OBJECT_NEW_FN' (aka 'void *(*)(void *)') from 'void *(const void *)' [-Wincompatible-function-pointer-types]
|         obj->fnObjectNew = uwac_event_clone;
|                          ^ ~~~~~~~~~~~~~~~~

When using clang, an error occured due to type mismatch.

2023-09-11 06:12 UTC, hardening commented
@freerdp-bot can you test please ?

2023-09-11 07:05 UTC, hardening approved these changes
LGTM

2023-09-11 07:58 UTC, akallabeth requested changes
definition of function pointer in `collections.h`: `typedef void* (*OBJECT_NEW_FN)(const void* val);` so how did you get a warning?

2023-09-11 08:17 UTC, wangmingyu84 commented
We use tag2.11.1, definition of function pointer in collections. h: typedef void * (* OBJECTNEW-FN) (void * val);

2023-09-11 08:51 UTC, akallabeth commented
@wangmingyu84 ah, ok, so you created the pull request against the wrong branch.
closing.

2023-09-11 08:51 UTC, closed without merging

2023-09-12 00:12 UTC, VVD commented
Can you merge to stable-2.0? Or 3.0 release is very soon?

2023-09-12 00:28 UTC, wangmingyu84 commented
I only made changes to fix the current issue according to the latest collections.h,  but did not include the whole latest collections.h.
Do I need to submit this modification to stable 2.0?

2023-09-13 11:39 UTC, VVD commented
stable-2.0 (and 2.11.1) have this bug too.