Fix some compilation issues.
FreeRDP/FreeRDP pull request #9620
Opened 2023-12-08 04:53 UTC by llyzs

2023-12-08 06:25 UTC, hardening commented
Hum can FreeRDP really work without any timer support ?

2023-12-08 07:21 UTC, llyzs commented
> Hum can FreeRDP really work without any timer support ?

"CreateWaitableTimer" search result shows that it is used only in client implementation, and libfreerdp does not use this function. It looks like the timer implementation in winpr is just a convenience for client implementation but not a required component.

We are currently investigating the possibility to use freerdp in WebAssembly and the wasm environment provides no such implementation.

2023-12-10 10:28 UTC, akallabeth requested changes

2023-12-10 10:28 UTC, akallabeth commented on winpr/libwinpr/crypto/cipher.c
> +	EVP_CIPHER_CTX_reset(ctx->ctx);
this is openssl >= 3.0 only, needs a preprocessor switch

2023-12-11 07:51 UTC, akallabeth approved these changes
Sorry, did miss it was already part of 1.1.1
only 1.0 is lacking this, so LGTM

2023-12-11 07:52 UTC, merged