Make rdp2tcp work again
FreeRDP/FreeRDP pull request #9738
Opened 2024-01-07 15:18 UTC by dexpl

Remove FREERDP_API from VirtualChannelEntryEx functon definition thus making FreeRDP recognize this code as a virtual channel plugin.

2024-01-07 16:41 UTC, akallabeth requested changes
does not make any sense.
do you try to build this channel outside freerdp or why do you need the `FREERDP_API VirtualChannelEntryEx` definition?

2024-01-12 11:32 UTC, dexpl commented
> does not make any sense. do you try to build this channel outside freerdp or why do you need the `FREERDP_API VirtualChannelEntryEx` definition?

Sorry, there's a mistake in my description: the patch actually adds FREERDP_API, not removes it. Without it remmina is unable to load librdp2tcp-client.so: if I create an RDP connection, set path to rdp2tcp binary in "Advanced"→"TCP redirection" and then try to connect, it fails with the following error message:
```
[14:23:41:463] [1176063:1176398] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure VirtualChannelEntryEx: /usr/lib64/freerdp2/librdp2tcp-client.so: undefined symbol: VirtualChannelEntryEx
[14:23:41:463] [1176063:1176398] [WARN][com.freerdp.addin] - Failed to load channel rdp2tcp [(nil)]
[14:23:41:463] [1176063:1176398] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure VirtualChannelEntry: /usr/lib64/freerdp2/librdp2tcp-client.so: undefined symbol: VirtualChannelEntry
[14:23:41:463] [1176063:1176398] [WARN][com.freerdp.addin] - Failed to load channel rdp2tcp [(nil)]
[14:23:41:463] [1176063:1176398] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure VirtualChannelEntryEx: /usr/lib64/freerdp2/librdp2tcp-client.so: undefined symbol: VirtualChannelEntryEx
[14:23:41:463] [1176063:1176398] [WARN][com.freerdp.addin] - Failed to load channel rdp2tcp [(nil)]
[14:23:41:464] [1176063:1176398] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure VirtualChannelEntry: /usr/lib64/freerdp2/librdp2tcp-client.so: undefined symbol: VirtualChannelEntry
[14:23:41:464] [1176063:1176398] [WARN][com.freerdp.addin] - Failed to load channel rdp2tcp [(nil)]
[14:23:41:464] [1176063:1176398] [ERROR][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex ERRCONNECT_PRE_CONNECT_FAILED [0x00020001]
[14:23:41:464] [1176063:1176398] [ERROR][com.freerdp.core] - freerdp_pre_connect failed
libfreerdp returned code is 00020001
```

Maybe I'm missing some build options? If so, gimme a hint, please.

2024-01-12 13:40 UTC, dexpl commented
Seems I know what should be done. Gonna make another PR though.

2024-01-12 13:40 UTC, closed without merging

2024-01-12 21:09 UTC, akallabeth commented
@dexpl what is your issue actually? that you use a freerdp that did not build rdp2tcp? which version are you using?