remove superfluous manpage build dependencies
FreeRDP/FreeRDP pull request #9805
Opened 2024-01-24 22:00 UTC by karmix

The `${manpage}.manpage` custom target in `generate_and_install_freerdp_man_from_xml` should only declare as dependencies the build targets we wish to add to `ALL`, and should not include the sub-dependencies of those build targets.

Resolves #9804

2024-01-25 08:51 UTC, akallabeth requested changes
while it can be reasoned that the dependencies should move to `add_custom_command` it is no solution just to delete this and hope for the best.

2024-01-25 23:28 UTC, karmix commented
I apologize for the confusion, I was not suggesting we hope for the best.  I explained why each of these dependencies was unnecessary in the discussion of the issue, here: https://github.com/FreeRDP/FreeRDP/issues/9804#issuecomment-1908976647

2024-01-26 10:02 UTC, akallabeth commented
@karmix you did rationalize your changes, but you missed that `generate_argument_docbook` is not in the dependency list of `add_custom_command(OUTPUT ${manpage}` in your pr

2024-01-27 03:09 UTC, karmix commented
`generate_argument_docbook` is listed as a `COMMAND`.  When commands reference executables that CMake builds (as is this case), it implicitly adds them as order-only dependencies of the custom command target.  As an order-only dependency, Ninja will ensure it gets built before the custom command runs.  (If that weren't the case, there would be nothing to ensure that order in the current rules :grin: .)

I didn't wan't to modify behavior in the initial PR.  Adding `generate_argument_docbook` as a standard dependency would deviate from current behavior by causing Ninja to rerun the custom command and refresh the manpage if `generate_argument_docbook` was updated/recompiled (where the order-only dependency does not trigger a refresh).  It isn't a bad idea to add this if you are going to be doing development work on the tool.  If you'd like, I can update the PR.

2024-01-29 07:41 UTC, akallabeth commented
> 
> I didn't wan't to modify behavior in the initial PR. Adding `generate_argument_docbook` as a standard dependency would deviate from current behavior by causing Ninja to rerun the custom command and refresh the manpage if `generate_argument_docbook` was updated/recompiled (where the order-only dependency does not trigger a refresh). It isn't a bad idea to add this if you are going to be doing development work on the tool. If you'd like, I can update the PR.

that was the whole point in having it in the dependency list ;)
the tool generates the data from compiling with current sources and extract data from a struct.

2024-01-29 07:44 UTC, akallabeth commented
replaced by #9813

2024-01-29 07:44 UTC, closed without merging