[sdl] Only blit rects to windows that they intersect
FreeRDP/FreeRDP pull request #9955
Opened 2024-03-08 21:39 UTC by caseif

This pull request modifies the `sdl_draw_to_window_rect` to skip attempting to blit rects which do not intersect the window the function is currently operating on. This prevents `SdlWindow#blit` from returning false and short-circuiting the drawing loop. In a single-window session, it's reasonable to assume that something is wrong if any of the rectangles being blitted do not interesect the window, but in a multimon session each rectangle will only be applicable for one window. Because the primary window is always handled first, all rectangles which intersect a different window will fail to be blitted to the primary one and immediately short-circuit the draw loop.

This PR doesn't modify the analogous functions for smart-sizing, because currently smart-sizing appears to be completely broken on SDL with multimon enabled.

2024-03-09 07:15 UTC, akallabeth requested changes
nice catch,
but I´d move the check to `sdl_draw_to_window_rect` and simply ignore regions that are not intesecting (without any multimonitor check)

there might arise scenarios where this will be true for even single monitor sessions, so no need to make it more complicated than necessary.

2024-03-09 07:28 UTC, akallabeth commented
on second thought, might be simplest to ignore these in `SdlWindow::blit`

2024-03-11 11:22 UTC, akallabeth commented
@caseif thank you for bringing this to my attention.
I´ve created #9962 to ignore `SdlWindow::blit` that does not intersect instead though, as we don´t necessarily know the updates intersect with the surface (even in single window mode, once we add resizeability without resolution changes)

2024-03-11 11:22 UTC, closed without merging

2024-03-11 15:14 UTC, caseif commented
Thanks for taking care of this. This was my initial thought but I was a bit nervous about potentially obscuring an error condition, but if that's not an issue then I agree it's a much nicer solution. :)